name = "haven-platform"
main = "src/worker.js"
compatibility_date = "2024-10-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "haven_db"
database_id = "YOUR_D1_DATABASE_ID"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Secrets (set with: wrangler secret put ANTHROPIC_API_KEY)
# ANTHROPIC_API_KEY (required)
# OPENAI_API_KEY (optional)

# Static assets for frontend
[site]
bucket = "./public"
